### ISSUE TITLE
Idea: Add ability to indicate minimum ascension/awakening level to tier lists

### ISSUE THREAD

**Issue by fraserstanton** [NieR-Rein-Guide/nierrein.guide#180]
I was curious for the character tier lists, if there is a minimum ascension/awakening level for the ranked characters?
e.g. Celebratory Songstress is the number 1 PVE SSS character, but would she only be recommended if ascended/awakened to max? Or would she still be recommended there with no ascensions/awakenings?

To give you an example, I show you the character tier list for genshin impact from game8 where it has a tier list for each character ascension level. https://game8.co/games/Genshin-Impact/archives/297465
This chart shows a minimum "constellation" level to be considered top tier.

It would mean that along with ownership that you would need a method to store awakening and ascension levels.
Anyway, just putting the idea out there.
Love your work so far btw.

**Comment by KeziahMoselle** [comment]
We are currently discussing this with the tierlists team and what we think so far is that the awakening levels are good-to-have bonuses but not mandatory for several costumes (not many) and all of them are still usable at awakening level 0.
We are still debating of adding that feature because I'm fearful that players will think the awakening level are required (they are not), so we are thinking on ways to add this feature without this negative side-effect

**Comment by KeziahMoselle** [comment]
ascension levels are always assumed to be lvl 90.

**Comment by fraserstanton** [comment]
Maybe adding details in the note is enough, since it is only a few that don't work well at 0 awakenings. I don't find I have enough advanced training books to get up to 90 with many. Guess I have to just use them on the best of the best.
I keep trying to use Yuletide Werebeast for DPS, but I don't have him awakened or ascended and he seems just terrible for me.
